---
title: "Farmers' preferences for tackling climate change: the case of agroforestry in Southeast Germany"
author: "Christian Stetter"
date: "1/8/2021"
output: html_document
---

# 1. Load libraries

```{r load libraries, include=FALSE}
library(support.CEs)
library(survival)
library(data.table)
library(mlogit)
library(broom)
library(tidyverse)
```

# 2. Data
## Prepare weather variables with different lag structure (Ramsey AJAE 2021)
```{r warning=FALSE}
df <- readRDS("~/weather_data/choice_data/fd_weather_plz.rds")
colnames(df) <- stringr::str_replace(colnames(df), "ann_", "") 
old_names <- c("rain", "temp", "dd", "r20", "hd")

df_weather <- cbind(
## 1-3 lags
df %>% filter(year>=2017 & year<=2019) %>%
 aggregate(., by = list(.$plz), FUN = mean) %>% 
 dplyr::select(Group.1, rain:hd) %>%
 rename_at(vars(colnames(.)), ~ c("zip", paste0(old_names, "_1_3" ))),

## 1 lag
df %>% filter(year==c(2019)) %>%
 aggregate(., by = list(.$plz), FUN = mean) %>% 
 dplyr::select(rain:hd) %>%
 rename_at(vars(colnames(.)), ~ c(paste0(old_names, "_1" ))),

## 1-5 lags
df %>% filter(year>=2015 & year<=2019) %>%
 aggregate(., by = list(.$plz), FUN = mean, na.rm=T) %>% 
 dplyr::select(rain:hd) %>%
 rename_at(vars(colnames(.)),~ c(paste0(old_names, "_1_5" ))),


## 2-10 lag
df %>% filter(year>=2010 & year<=2018) %>%
 aggregate(., by = list(.$plz), FUN = mean) %>% 
 dplyr::select(rain:hd) %>%
 rename_at(vars(colnames(.)), ~ c(paste0(old_names, "_2_10" ))),

## 2-15 lag
df %>% filter(year>=2005 & year<=2018) %>%
 aggregate(., by = list(.$plz), FUN = mean) %>% 
 dplyr::select(rain:hd) %>%
 rename_at(vars(colnames(.)), ~ c(paste0(old_names, "_2_15" ))),

## 2-20 lag
df %>% filter(year>=2000 & year<=2018) %>%
 aggregate(., by = list(.$plz), FUN = mean) %>% 
 dplyr::select(rain:hd) %>%
 rename_at(vars(colnames(.)), ~ c(paste0(old_names, "_2_20" ))),


## 2-25 lag
df %>% filter(year>=1995 & year<=2018) %>%
 aggregate(., by = list(.$plz), FUN = mean) %>% 
 dplyr::select(rain:hd) %>%
 rename_at(vars(colnames(.)), ~ c(paste0(old_names, "_2_25" ))),


## 4-10 lag
df %>% filter(year>=2010 & year<=2016) %>%
 aggregate(., by = list(.$plz), FUN = mean) %>% 
 dplyr::select(rain:hd) %>%
 rename_at(vars(colnames(.)), ~ c(paste0(old_names, "_4_10" ))),

## 4-15 lag
df %>% filter(year>=2005 & year<=2016) %>%
 aggregate(., by = list(.$plz), FUN = mean) %>% 
 dplyr::select(rain:hd) %>%
 rename_at(vars(colnames(.)), ~ c(paste0(old_names, "_4_15" ))),

## 4-20 lag
df %>% filter(year>=2000 & year<=2016) %>%
 aggregate(., by = list(.$plz), FUN = mean) %>% 
 dplyr::select(rain:hd) %>%
 rename_at(vars(colnames(.)), ~ c(paste0(old_names, "_4_20" ))),


## 4-25 lag
df %>% filter(year>=1995 & year<=2016) %>%
 aggregate(., by = list(.$plz), FUN = mean) %>% 
 dplyr::select(rain:hd) %>%
 rename_at(vars(colnames(.)), ~ c(paste0(old_names, "_4_25" ))),


## 6-10 lag
df %>% filter(year>=2010 & year<=2014) %>%
 aggregate(., by = list(.$plz), FUN = mean) %>% 
 dplyr::select(rain:hd) %>%
 rename_at(vars(colnames(.)), ~ c(paste0(old_names, "_6_10" ))),

## 6-15 lag
df %>% filter(year>=2005 & year<=2014) %>%
 aggregate(., by = list(.$plz), FUN = mean) %>% 
 dplyr::select(rain:hd) %>%
 rename_at(vars(colnames(.)), ~ c(paste0(old_names, "_6_15" ))),

## 6-20 lag
df %>% filter(year>=2000 & year<=2014) %>%
 aggregate(., by = list(.$plz), FUN = mean) %>% 
 dplyr::select(rain:hd) %>%
 rename_at(vars(colnames(.)), ~ c(paste0(old_names, "_6_20" ))),


## 6-25 lag
df %>% filter(year>=1995 & year<=2014) %>%
 aggregate(., by = list(.$plz), FUN = mean) %>% 
 dplyr::select(rain:hd) %>%
 rename_at(vars(colnames(.)), ~ c(paste0(old_names, "_6_25" ))),


## 50 years baseline
df %>% filter(year>=1971 & year<=2020) %>%
 aggregate(., by = list(.$plz), FUN = mean) %>% 
 dplyr::select(rain:hd) %>%
 rename_at(vars(colnames(.)), ~ c(paste0(old_names, "_base" ))),

df %>% filter(year>=1991 & year<=2020) %>%
 aggregate(., by = list(.$plz), FUN = mean) %>% 
 dplyr::select(rain:hd) %>%
 rename_at(vars(colnames(.)), ~ c(paste0(old_names, "_base30" ))),

df %>% filter(year==2018) %>%
 aggregate(., by = list(.$plz), FUN = mean) %>% 
 dplyr::select(rain:hd) %>%
 rename_at(vars(colnames(.)), ~ c(paste0(old_names, "_drought_year")))
)
```



## 2.1 Load data
```{r}
design_matrix <- readRDS("design_matrix.rds")
dat <- readRDS("data_calc.rds") %>%
  left_join(.,df_weather, by="zip")

## mean-center weather variables 
start=which(colnames(dat)=="rain_1_3")
end=which(colnames(dat)=="hd_drought_year")
for (i in start:end) {
        dat[[paste0(colnames(dat)[i], "_c")]] <-
                dat[[i]] - mean(dat[[i]], na.rm = T)
}
```

# 3. Descriptive Statistics
```{r}
library(rgdal)
library(sf)
library(ggplot2)
#### Load shape data ####
shape <- sf::st_read("~/weather_data/choice_data/plz-3stellig.shp")

## subset only relevant zip codes
shape <- shape[startsWith(shape$plz, "63") | 
                startsWith(shape$plz, "8") | 
                startsWith(shape$plz, "9"),]

shape5 <- sf::st_read("~/weather_data/choice_data/plz-gebiete.shp")
shape5 <- shape5[ which(shape5$plz %in% 
                          dat$location[which(nchar(dat$location)==5)]),]

shape5$note <- NULL
shapeAll <- rbind(shape, shape5)

shapeAll <- shapeAll %>% 
 group_by(plz) %>%
 summarise(geometry = sf::st_union(geometry)) %>%
 ungroup()

a <- st_centroid(shapeAll)

new <- table(dat$zip) %>% as.data.frame %>% rename(plz=Var1)
b <- left_join(new, a)
test <- left_join(shapeAll, b, by="plz")

a <- st_centroid(shapeAll)

new <- table(dat$zip) %>% as.data.frame %>% rename(plz=Var1)
b <- left_join(new, a)
test <- left_join(shapeAll, b, by="plz")

BYshape <- sf::st_read("~/weather_data/choice_data/bayern_ex.shp")[,"SCH"]
BYshape <- st_transform(BYshape, st_crs(shapeAll))
BYshapeRB <- sf::st_read("~/weather_data/choice_data/regbez_ex.shp")[,"SCH"]
BYshapeRB <- st_transform(BYshapeRB, st_crs(shapeAll))
BYshapeBodKLim <- sf::st_read("~/weather_data/choice_data/bkr.gpkg")
BYshapeBodKLim <- st_transform(BYshapeBodKLim, st_crs(shapeAll))

shapeAll <- st_intersection(shapeAll, BYshape)
BYshapeBodKLim <- st_intersection(BYshapeBodKLim, BYshape)

BYshapeBodKLim$BKR <- with(BYshapeBodKLim, case_when(
  BKR10_ID  == 117 | BKR10_ID  == 199 | BKR10_ID  == 120 ~ 117,
  BKR10_ID  == 116 ~ 116,
  BKR10_ID  == 115 ~ 115,
  BKR10_ID  == 114 ~ 114,
  BKR10_ID  == 112 | BKR10_ID  == 111 | BKR10_ID  == 194 | BKR10_ID  == 195
  | BKR10_ID  == 196 ~ 112,
  BKR10_ID  == 113 | BKR10_ID  == 130 | BKR10_ID  == 132 |
    BKR10_ID  == 193 | BKR10_ID  == 121 ~ 113))

BYshapeBodKLimAgg <- BYshapeBodKLim %>%
  group_by(BKR = BKR)  %>% 
  summarize(geometry = st_union(geom)) %>%
  ungroup()


shapeCentroidBodKLimAgg <- st_join(a, BYshapeBodKLimAgg, join = st_intersects,
                    largest=T) %>% 
  select(plz, BKR)

shapeAllRB <- st_join(shapeAll, BYshapeRB, join = st_intersects,
                    largest=T) %>%
  mutate(SCH = SCH.y) %>%
  select(plz, SCH)

shapeAll_multi <- st_join(shapeAll, BYshapeRB, join = st_intersects)

colnames(shapeAll_multi)[1] <- colnames(shapeAllRB)[1] <-  colnames(shapeCentroidBodKLimAgg)[1] <-"zip"

dat <- left_join(dat, shapeAllRB, by="zip")  %>%
  left_join(., shapeCentroidBodKLimAgg, by="zip")

dat <- filter(dat, !is.na(SCH) & !is.na(BKR))
dat_sim_multi <- left_join(dat, shapeAll_multi, by="zip")

b <- b[b$plz %in% dat$zip,]
gg_sample_spatial <- ggplot(data = BYshapeBodKLimAgg) +
    geom_sf(aes(fill = as.factor(BKR)), color = gray(.5), alpha=0.2) +
 geom_point(data = b, color="red", alpha = .5,
            aes(size = Freq, geometry = geometry),
            stat = "sf_coordinates") +
 scale_size_continuous(range = c(1, 3), breaks = c(1,3,5,7)) +
 theme(panel.grid = element_blank(), 
       axis.title = element_blank(),
       axis.text = element_blank(),
       axis.ticks = element_blank(),
       panel.background = element_blank(),
       panel.border = element_rect(colour = "black", fill=NA),
       legend.position=c(.9,.8))
```


## 2.1 Prepare data for estimation with mlogit and glmn
```{r}
df <- make.dataset(
respondent.dataset = dat,
choice.indicators =
c("q1", "q2", "q3", "q4", "q5","q6", "q7", "q8", "q9", "q10", "q11", "q12"),
design.matrix = design_matrix)

df$group <- with(df, ifelse( RES == TRUE, ALT, NA))
df$choice <- with(df, ave(group, QES, ID, FUN=function(i) mean(i, na.rm=T)))

df[seq(3, nrow(df), 3), c("DB", "DBVar", "ND", "AU", "No") ] <- 
  matrix(rep(c(400, 15, 3, 0, 1), each = nrow(df)/3), ncol = 5)

df$DBVar_high <- ifelse(df$DBVar == 30, 1, 0)
df$ND_long <- ifelse(df$ND == 24, 1, 0)
df$ND_medium <- ifelse(df$ND == 20, 1, 0)

df_mlogit <- reshape(df,
                     v.names = c("DB", "DBVar", "ND", "AU", "No", "DBVar_high",
                                 "ND_long", "ND_medium"),
                     idvar=c("ID", "BLOCK", "QES"),
                     timevar = "ALT",
                     direction="wide")

df_mlogit$CHID <- 1:nrow(df_mlogit)

start=which(colnames(df_mlogit)=="DB.1")
end=which(colnames(df_mlogit)=="ND_medium.3")

dfm <- df_mlogit %>% as.data.frame() %>% dfidx(idx = list(c("CHID", "ID")), 
                                               choice = "choice", 
                                               varying = start:end, sep = ".")

dfml <- df_mlogit %>% as.data.frame() %>% mlogit.data(chid.var =  "CHID",
                                                     id.var = "ID", 
                                                     choice = "choice", 
                                                     varying = start:end, sep = ".")
```
# 4. Models 1_3, 4_10

## Baseline
```{r abs change rates 25, eval=FALSE, include=FALSE}
res_cor_base_13_410 <- mlogit(choice ~ DB + DBVar + ND + AU + No | 1,
               data = dfm, 
               panel = T,
               rpar = c(DB = "ln", DBVar = "n", ND = "n", AU = "n", No = "n",
                        "(Intercept):1"="n", 
                        "(Intercept):2"="n"),
               R = 1000, 
               correlation = T, 
               halton = NA, 
               method = "bhhh",
               reflevel = 3, 
               seed = 3)

res_uncor_base_13_410 <- update(res_cor_base_13_410, correlation = F)
# 
# lrtest(resBASEcor, resBASEuncor)
# 
# summary(resBASEuncor);summary(resBASEuncor)
```

##ln n model

```{r abs change rates 25}
res_cor_13_410 <- mlogit(choice ~ DB + DBVar + ND + AU + No |  
           rain_1_3_c + 
           rain_4_10_c +
           temp_1_3_c + 
           temp_4_10_c +
           dd_1_3_c +
           dd_4_10_c +
           r20_1_3_c +
           r20_4_10_c +
           hd_1_3_c +
           hd_4_10_c,
         data = dfml, 
         panel = T, 
         rpar = c(DB = "ln", DBVar = "n", ND = "n", AU = "n", No = "n",
                  "(Intercept):1"="n", "(Intercept):2"="n",
                  "rain_1_3_c:1"="n",
                  "rain_4_10_c:1"="n",
                  "temp_1_3_c:1"="n",
                  "temp_4_10_c:1"="n",
                  "dd_1_3_c:1"="n",
                  "dd_4_10_c:1"="n",
                  "r20_1_3_c:1"="n",
                  "r20_4_10_c:1"="n",
                  "hd_1_3_c:1"="n",
                  "hd_4_10_c:1"="n",
         
                  "rain_1_3_c:2"="n",
                  "rain_4_10_c:2"="n",
                  "temp_1_3_c:2"="n",
                  "temp_4_10_c:2"="n",
                  "dd_1_3_c:2"="n",
                  "dd_4_10_c:2"="n",
                  "r20_1_3_c:2"="n",
                  "r20_4_10_c:2"="n",
                  "hd_1_3_c:2"="n",
                  "hd_4_10_c:2"="n"),
         R = 1000, 
         correlation =  c("DB", "DBVar", "ND", "AU", "No",
                          "(Intercept):1", "(Intercept):2"), 
         halton = NULL, 
               method = "bhhh",
               reflevel = 3, 
               seed = 3,
               iterlim = 2000)

res_uncor_13_410 <- update(res_cor_13_410, correlation = F)
# 
# saveRDS(resCR25cor_bhhh, "model_output/resCR25cor_bhhh.rds")
# saveRDS(object = resCR25_nln_cor_bhhh555, file = "model_output/resCR25_alln_uncor_bhhh555.rds")
```


##  n n model

```{r abs change rates 25}
res_cor_nn_13_410 <- mlogit(choice ~ DB + DBVar + ND + AU + No |  
           rain_1_3_c + 
           rain_4_10_c +
           temp_1_3_c + 
           temp_4_10_c +
           dd_1_3_c +
           dd_4_10_c +
           r20_1_3_c +
           r20_4_10_c +
           hd_1_3_c +
           hd_4_10_c,
         data = dfml, 
         panel = T, 
         rpar = c(DB = "n", DBVar = "n", ND = "n", AU = "n", No = "n",
                  "(Intercept):1"="n", "(Intercept):2"="n",
                  "rain_1_3_c:1"="n",
                  "rain_4_10_c:1"="n",
                  "temp_1_3_c:1"="n",
                  "temp_4_10_c:1"="n",
                  "dd_1_3_c:1"="n",
                  "dd_4_10_c:1"="n",
                  "r20_1_3_c:1"="n",
                  "r20_4_10_c:1"="n",
                  "hd_1_3_c:1"="n",
                  "hd_4_10_c:1"="n",
         
                  "rain_1_3_c:2"="n",
                  "rain_4_10_c:2"="n",
                  "temp_1_3_c:2"="n",
                  "temp_4_10_c:2"="n",
                  "dd_1_3_c:2"="n",
                  "dd_4_10_c:2"="n",
                  "r20_1_3_c:2"="n",
                  "r20_4_10_c:2"="n",
                  "hd_1_3_c:2"="n",
                  "hd_4_10_c:2"="n"),
         R = 1000, 
         correlation =  c("DB", "DBVar", "ND", "AU", "No",
                          "(Intercept):1", "(Intercept):2"), 
         halton = NULL, 
               method = "bhhh",
               reflevel = 3, 
               seed = 3,
               iterlim = 2000)
# resCR25uncorNN_bhhh <- update(resCR25corNN_bhhh, correlation = F)
```


##  ln ln model

```{r abs change rates 25}
res_cor_lnln_13_410 <- mlogit(choice ~ DB + DBVar + ND + AU + No |  
           rain_1_3_c + 
           rain_4_10_c +
           temp_1_3_c + 
           temp_4_10_c +
           dd_1_3_c +
           dd_4_10_c +
           r20_1_3_c +
           r20_4_10_c +
           hd_1_3_c +
           hd_4_10_c,
         data = dfml, 
         panel = T, 
         rpar = c(DB = "ln", DBVar = "n", ND = "n", AU = "ln", No = "n",
                  "(Intercept):1"="n", "(Intercept):2"="n",
                  "rain_1_3_c:1"="n",
                  "rain_4_10_c:1"="n",
                  "temp_1_3_c:1"="n",
                  "temp_4_10_c:1"="n",
                  "dd_1_3_c:1"="n",
                  "dd_4_10_c:1"="n",
                  "r20_1_3_c:1"="n",
                  "r20_4_10_c:1"="n",
                  "hd_1_3_c:1"="n",
                  "hd_4_10_c:1"="n",
         
                  "rain_1_3_c:2"="n",
                  "rain_4_10_c:2"="n",
                  "temp_1_3_c:2"="n",
                  "temp_4_10_c:2"="n",
                  "dd_1_3_c:2"="n",
                  "dd_4_10_c:2"="n",
                  "r20_1_3_c:2"="n",
                  "r20_4_10_c:2"="n",
                  "hd_1_3_c:2"="n",
                  "hd_4_10_c:2"="n"),
         R = 1000, 
         correlation =  c("DB", "DBVar", "ND", "AU", "No",
                          "(Intercept):1", "(Intercept):2"), 
         halton = NULL, 
               method = "bhhh",
               reflevel = 3, 
               seed = 3,
               iterlim = 2000)
```



# 5. Robustness checks for ln n model
## 1 - 2_10 model
```{r}
resCR25cor_1_210 <- mlogit(choice ~ DB + DBVar + ND + AU + No |  
                       rain_1_c + 
                       rain_2_10_c +
                       temp_1_c + 
                       temp_2_10_c +
                       dd_1_c +
                       dd_2_10_c +
                       r20_1_c +
                       r20_2_10_c +
                       hd_1_c +
                       hd_2_10_c,
               data = dfm, 
               panel = T, 
               rpar = c(DB = "ln", DBVar = "n", ND = "n", AU = "ln", No = "n",
                  "(Intercept):1"="n", "(Intercept):2"="n",
                  "rain_1_c:1"="n",
                  "rain_2_10_c:1"="n",
                  "temp_1_c:1"="n",
                  "temp_2_10_c:1"="n",
                  "dd_1_c:1"="n",
                  "dd_2_10_c:1"="n",
                  "r20_1_c:1"="n",
                  "r20_2_10_c:1"="n",
                  "hd_1_c:1"="n",
                  "hd_2_10_c:1"="n",
         
                  "rain_1_c:2"="n",
                  "rain_2_10_c:2"="n",
                  "temp_1_c:2"="n",
                  "temp_2_10_c:2"="n",
                  "dd_1_c:2"="n",
                  "dd_2_10_c:2"="n",
                  "r20_1_c:2"="n",
                  "r20_2_10_c:2"="n",
                  "hd_1_c:2"="n",
                  "hd_2_10_c:2"="n"),
         R = 1000, 
         correlation =  c("DB", "DBVar", "ND", "AU", "No",
                          "(Intercept):1", "(Intercept):2"), 
         halton = NULL, 
               method = "bhhh",
               reflevel = 3, 
               seed = 1,
               iterlim = 2000)
```

## 1 - 2_15 model
```{r}
resCR25cor_1_215 <- mlogit(choice ~ DB + DBVar + ND + AU + No |  
                       rain_1_c + 
                       rain_2_15_c +
                       temp_1_c + 
                       temp_2_15_c +
                       dd_1_c +
                       dd_2_15_c +
                       r20_1_c +
                       r20_2_15_c +
                       hd_1_c +
                       hd_2_15_c,
               data = dfm, 
               panel = T, 
               rpar = c(DB = "ln", DBVar = "n", ND = "n", AU = "ln", No = "n",
                  "(Intercept):1"="n", "(Intercept):2"="n",
                  "rain_1_c:1"="n",
                  "rain_2_15_c:1"="n",
                  "temp_1_c:1"="n",
                  "temp_2_15_c:1"="n",
                  "dd_1_c:1"="n",
                  "dd_2_15_c:1"="n",
                  "r20_1_c:1"="n",
                  "r20_2_15_c:1"="n",
                  "hd_1_c:1"="n",
                  "hd_2_15_c:1"="n",
         
                  "rain_1_c:2"="n",
                  "rain_2_15_c:2"="n",
                  "temp_1_c:2"="n",
                  "temp_2_15_c:2"="n",
                  "dd_1_c:2"="n",
                  "dd_2_15_c:2"="n",
                  "r20_1_c:2"="n",
                  "r20_2_15_c:2"="n",
                  "hd_1_c:2"="n",
                  "hd_2_15_c:2"="n"),
         R = 1000, 
         correlation =  c("DB", "DBVar", "ND", "AU", "No",
                          "(Intercept):1", "(Intercept):2"), 
         halton = NULL, 
               method = "bhhh",
               reflevel = 3, 
               seed = 1,
               iterlim = 2000)
```


## 1 - 2_20 model
```{r}
resCR25cor_1_220 <- mlogit(choice ~ DB + DBVar + ND + AU + No |  
                       rain_1_c + 
                       rain_2_20_c +
                       temp_1_c + 
                       temp_2_20_c +
                       dd_1_c +
                       dd_2_20_c +
                       r20_1_c +
                       r20_2_20_c +
                       hd_1_c +
                       hd_2_20_c,
               data = dfm, 
               panel = T, 
               rpar = c(DB = "ln", DBVar = "n", ND = "n", AU = "ln", No = "n",
                  "(Intercept):1"="n", "(Intercept):2"="n",
                  "rain_1_c:1"="n",
                  "rain_2_20_c:1"="n",
                  "temp_1_c:1"="n",
                  "temp_2_20_c:1"="n",
                  "dd_1_c:1"="n",
                  "dd_2_20_c:1"="n",
                  "r20_1_c:1"="n",
                  "r20_2_20_c:1"="n",
                  "hd_1_c:1"="n",
                  "hd_2_20_c:1"="n",
         
                  "rain_1_c:2"="n",
                  "rain_2_20_c:2"="n",
                  "temp_1_c:2"="n",
                  "temp_2_20_c:2"="n",
                  "dd_1_c:2"="n",
                  "dd_2_20_c:2"="n",
                  "r20_1_c:2"="n",
                  "r20_2_20_c:2"="n",
                  "hd_1_c:2"="n",
                  "hd_2_20_c:2"="n"),
         R = 1000, 
         correlation =  c("DB", "DBVar", "ND", "AU", "No",
                          "(Intercept):1", "(Intercept):2"), 
         halton = NULL, 
               method = "bhhh",
               reflevel = 3, 
               seed = 1,
               iterlim = 2000)
```



## 1_3 - 4_15 model
```{r}
resCR25cor_13_415 <- mlogit(choice ~ DB + DBVar + ND + AU + No |  
                       rain_1_3_c + 
                       rain_4_15_c +
                       temp_1_3_c + 
                       temp_4_15_c +
                       dd_1_3_c +
                       dd_4_15_c +
                       r20_1_3_c +
                       r20_4_15_c +
                       hd_1_3_c +
                       hd_4_15_c,
               data = dfm, 
               panel = T, 
               rpar = c(DB = "ln", DBVar = "n", ND = "n", AU = "ln", No = "n",
                  "(Intercept):1"="n", "(Intercept):2"="n",
                  "rain_1_3_c:1"="n",
                  "rain_4_15_c:1"="n",
                  "temp_1_3_c:1"="n",
                  "temp_4_15_c:1"="n",
                  "dd_1_3_c:1"="n",
                  "dd_4_15_c:1"="n",
                  "r20_1_3_c:1"="n",
                  "r20_4_15_c:1"="n",
                  "hd_1_3_c:1"="n",
                  "hd_4_15_c:1"="n",
         
                  "rain_1_3_c:2"="n",
                  "rain_4_15_c:2"="n",
                  "temp_1_3_c:2"="n",
                  "temp_4_15_c:2"="n",
                  "dd_1_3_c:2"="n",
                  "dd_4_15_c:2"="n",
                  "r20_1_3_c:2"="n",
                  "r20_4_15_c:2"="n",
                  "hd_1_3_c:2"="n",
                  "hd_4_15_c:2"="n"),
         R = 1000, 
         correlation =  c("DB", "DBVar", "ND", "AU", "No",
                          "(Intercept):1", "(Intercept):2"), 
         halton = NULL, 
               method = "bhhh",
               reflevel = 3, 
               seed = 1,
               iterlim = 2000)
```


## 1_3 - 4_20 model
```{r}
resCR25cor_13_420 <- mlogit(choice ~ DB + DBVar + ND + AU + No |  
                       rain_1_3_c + 
                       rain_4_20_c +
                       temp_1_3_c + 
                       temp_4_20_c +
                       dd_1_3_c +
                       dd_4_20_c +
                       r20_1_3_c +
                       r20_4_20_c +
                       hd_1_3_c +
                       hd_4_20_c,
               data = dfm, 
               panel = T, 
               rpar = c(DB = "ln", DBVar = "n", ND = "n", AU = "ln", No = "n",
                  "(Intercept):1"="n", "(Intercept):2"="n",
                  "rain_1_3_c:1"="n",
                  "rain_4_20_c:1"="n",
                  "temp_1_3_c:1"="n",
                  "temp_4_20_c:1"="n",
                  "dd_1_3_c:1"="n",
                  "dd_4_20_c:1"="n",
                  "r20_1_3_c:1"="n",
                  "r20_4_20_c:1"="n",
                  "hd_1_3_c:1"="n",
                  "hd_4_20_c:1"="n",
         
                  "rain_1_3_c:2"="n",
                  "rain_4_20_c:2"="n",
                  "temp_1_3_c:2"="n",
                  "temp_4_20_c:2"="n",
                  "dd_1_3_c:2"="n",
                  "dd_4_20_c:2"="n",
                  "r20_1_3_c:2"="n",
                  "r20_4_20_c:2"="n",
                  "hd_1_3_c:2"="n",
                  "hd_4_20_c:2"="n"),
         R = 1000, 
         correlation =  c("DB", "DBVar", "ND", "AU", "No",
                          "(Intercept):1", "(Intercept):2"), 
         halton = NULL, 
               method = "bhhh",
               reflevel = 3, 
               seed = 1,
               iterlim = 2000)
```


## 1_5 - 6_10 model
```{r}
resCR25cor_15_610 <- mlogit(choice ~ DB + DBVar + ND + AU + No |  
                       rain_1_5_c + 
                       rain_6_10_c +
                       temp_1_5_c + 
                       temp_6_10_c +
                       dd_1_5_c +
                       dd_6_10_c +
                       r20_1_5_c +
                       r20_6_10_c +
                       hd_1_5_c +
                       hd_6_10_c,
               data = dfm, 
               panel = T, 
                rpar = c(DB = "ln", DBVar = "n", ND = "n", AU = "ln", No = "n",
                  "(Intercept):1"="n", "(Intercept):2"="n",
                  "rain_1_5_c:1"="n",
                  "rain_6_10_c:1"="n",
                  "temp_1_5_c:1"="n",
                  "temp_6_10_c:1"="n",
                  "dd_1_5_c:1"="n",
                  "dd_6_10_c:1"="n",
                  "r20_1_5_c:1"="n",
                  "r20_6_10_c:1"="n",
                  "hd_1_5_c:1"="n",
                  "hd_6_10_c:1"="n",
         
                  "rain_1_5_c:2"="n",
                  "rain_6_10_c:2"="n",
                  "temp_1_5_c:2"="n",
                  "temp_6_10_c:2"="n",
                  "dd_1_5_c:2"="n",
                  "dd_6_10_c:2"="n",
                  "r20_1_5_c:2"="n",
                  "r20_6_10_c:2"="n",
                  "hd_1_5_c:2"="n",
                  "hd_6_10_c:2"="n"),
         R = 1000, 
         correlation =  c("DB", "DBVar", "ND", "AU", "No",
                          "(Intercept):1", "(Intercept):2"), 
         halton = NULL, 
               method = "bhhh",
               reflevel = 3, 
               seed = 1,
               iterlim = 2000)
```


## 1_5 - 6_15 model
```{r}
resCR25cor_15_615 <- mlogit(choice ~ DB + DBVar + ND + AU + No |  
                       rain_1_5_c + 
                       rain_6_15_c +
                       temp_1_5_c + 
                       temp_6_15_c +
                       dd_1_5_c +
                       dd_6_15_c +
                       r20_1_5_c +
                       r20_6_15_c +
                       hd_1_5_c +
                       hd_6_15_c,
               data = dfm, 
               panel = T, 
                 rpar = c(DB = "ln", DBVar = "n", ND = "n", AU = "ln", No = "n",
                  "(Intercept):1"="n", "(Intercept):2"="n",
                  "rain_1_5_c:1"="n",
                  "rain_6_15_c:1"="n",
                  "temp_1_5_c:1"="n",
                  "temp_6_15_c:1"="n",
                  "dd_1_5_c:1"="n",
                  "dd_6_15_c:1"="n",
                  "r20_1_5_c:1"="n",
                  "r20_6_15_c:1"="n",
                  "hd_1_5_c:1"="n",
                  "hd_6_15_c:1"="n",
         
                  "rain_1_5_c:2"="n",
                  "rain_6_15_c:2"="n",
                  "temp_1_5_c:2"="n",
                  "temp_6_15_c:2"="n",
                  "dd_1_5_c:2"="n",
                  "dd_6_15_c:2"="n",
                  "r20_1_5_c:2"="n",
                  "r20_6_15_c:2"="n",
                  "hd_1_5_c:2"="n",
                  "hd_6_15_c:2"="n"),
         R = 1000, 
         correlation =  c("DB", "DBVar", "ND", "AU", "No",
                          "(Intercept):1", "(Intercept):2"), 
         halton = NULL, 
               method = "bhhh",
               reflevel = 3, 
               seed = 1,
               iterlim = 2000)
```


## 1_5 - 6_10 model
```{r}
resCR25cor_15_620 <- mlogit(choice ~ DB + DBVar + ND + AU + No |  
                       rain_1_5_c + 
                       rain_6_20_c +
                       temp_1_5_c + 
                       temp_6_20_c +
                       dd_1_5_c +
                       dd_6_20_c +
                       r20_1_5_c +
                       r20_6_20_c +
                       hd_1_5_c +
                       hd_6_20_c,
               data = dfm, 
               panel = T, 
                  rpar = c(DB = "ln", DBVar = "n", ND = "n", AU = "ln", No = "n",
                  "(Intercept):1"="n", "(Intercept):2"="n",
                  "rain_1_5_c:1"="n",
                  "rain_6_20_c:1"="n",
                  "temp_1_5_c:1"="n",
                  "temp_6_20_c:1"="n",
                  "dd_1_5_c:1"="n",
                  "dd_6_20_c:1"="n",
                  "r20_1_5_c:1"="n",
                  "r20_6_20_c:1"="n",
                  "hd_1_5_c:1"="n",
                  "hd_6_20_c:1"="n",
         
                  "rain_1_5_c:2"="n",
                  "rain_6_20_c:2"="n",
                  "temp_1_5_c:2"="n",
                  "temp_6_20_c:2"="n",
                  "dd_1_5_c:2"="n",
                  "dd_6_20_c:2"="n",
                  "r20_1_5_c:2"="n",
                  "r20_6_20_c:2"="n",
                  "hd_1_5_c:2"="n",
                  "hd_6_20_c:2"="n"),
         R = 1000, 
         correlation =  c("DB", "DBVar", "ND", "AU", "No",
                          "(Intercept):1", "(Intercept):2"), 
         halton = NULL, 
               method = "bhhh",
               reflevel = 3, 
               seed = 1,
               iterlim = 2000)
```

# 6. AIC and LR tests
```{r}
sapply(
list(resCR25cor_1_210, 
     res_cor_13_410, 
     resCR25cor_13_415, 
     resCR25cor_13_420, 
     resCR25cor_15_615, 
     resCR25cor_15_620), AIC)

lrtest(resCR25cor_bhhh, resCR25cor_13_415)
```
